spring:
  springfox:
    documentation:
      auto-startup: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  thymeleaf:
    cache: false
    check-template-location: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    url: jdbc:mysql://ballast.proxy.rlwy.net:22537/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: OoJiJzxegPZmWPCRpbSJPURlKzrvVUpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # có thể đổi sang create để tạo mới DB khi lần đầu deploy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    show-sql: true
  # ===================== REDIS SESSION STORE =====================
  session:
    store-type: redis

  redis:
    host: redis-12018.c326.us-east-1-3.ec2.redns.redis-cloud.com
    port: 12018
    password: F6ok50nxNzzSiM9Fhl3hjHfBDXPp1gGP
    ssl: true

server:
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
  port: 8080

  logging:
    level:
      root: info
      file:
        name: log/dev.log
cloudinary:
          cloud_name: dmuqwyece
          api_key: 271778999598221
          api_secret: pjdTPJJMsBrKB7ui1Sdn5wgLV9o